# Generated by Django 5.1.6 on 2025-03-13 14:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('solicitante', models.CharField(max_length=100, verbose_name='Solicitantes')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('descricao', models.TextField(verbose_name='Descrição do chamado')),
                ('resolucao', models.TextField(blank=True, null=True, verbose_name='Resolução do chamado')),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'ABERTO'), ('EM_ATENDIMENTO', 'EM ATENDIMENTO'), ('ENCERRADA', 'ENCERRADA'), ('CANCELADA', 'CANCELADA')], default='ABERTO', max_length=15, verbose_name='Status')),
                ('finalizado_em', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ticket_cliente', to='clientes.cliente', verbose_name='CLIENTE')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_tick', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
